### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by larshp** [abapGit/icon-font#1]
there are multiple security issues in the current dependencies

**Comment by sbcgua** [comment]
have been fixing this in my repo for a while ... so can commit.

I have a strange issue - I pushed the changes to "changes branch" but what I do a PR most of the changes are not there ... although in the branch I see all accumulated commits ... have you seen this before ?

P.S. I added greenkeeper to my repo. Never used it before and decided to try ... but it actually does not do npm audit. Very sadly. I even knocked to the support and they replied that "it's planned in some future". Disappointed :(

**Comment by larshp** [comment]
changes branch, nah, guess it matches?

tried switching on the automatic security fixes from github
