### ISSUE TITLE
Create a CI process to build list of current icons and publish them as github page

### ISSUE THREAD

**Issue by sbcgua** [abapGit/icon-font#10]
ref https://github.com/abapGit/abapGit/pull/4165

`npm run build` does create it. Just to find the way to link it into some branch and publish somehow.

**Comment by larshp** [comment]
instead of a branch, I suggest creating https://icons.abapgit.org and then a new repo for that homepage, much like the other ones, https://github.com/abapGit?q=abapgit.org&type=&language=&sort=

**Comment by sbcgua** [comment]
good idea, so ... could you please create such a repo. And probably add a deployment key for it to this one for ci. I can have a look at the script

**Comment by larshp** [comment]
created, you should have admin access now in both repos, so you can add deploy keys

**Comment by sbcgua** [comment]
@larshp sorry for some delay, wrestling with work, it is a strong opponent :)

I read the https://github.com/peaceiris/actions-gh-pages action attentively - it actually allows deploying to another branch of the same repo (gh-pages in our case). And also specifying cname to that. I think we don't need an extra repo. Let's try this approach. But as I understand the gh-pages must be enabled in the settings - https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token - and I don't have an access there (no admin access ...). Could you pls try enabling it ? I've set the cname to icons2.abapgit.org for now.

P.S. BTW the GITHUB_TOKEN feature seems to be rather unsecure. I changed the workflow in PR and it uses GITHUB_TOKEN ... hmmm ... maybe there is a setting for this ... but don't turn it off yet

**Comment by larshp** [comment]
All 6 abapGit domains currently use the approach to have a separate repo, here is why:

Notifications happen on the repository level, with a separate repo, users can actively choose to watch the auto generated code being updated or not.

Performance: Having a separate repo keeps the source smaller, in the beginning of using gh-pages in the abapGit repo, the gh-pages branch was actually larger than the source code. We need to optimize for changing the source code

Security: Having one source and one generated repo makes better security when using deploy keys, as only the auto generated repo can be updated. Updating the source repo allows the generation to technically update the source

Administration: [Searching](https://github.com/abapGit?q=.org&type=&language=&sort=) allows to quickly get an overview of which domains there are and what they contain, this helps me a lot when having to administer 20+ subdomains across organizations

**Comment by sbcgua** [comment]
OK, make sense, agreed. Could you make me an admin of this repo then ? I don't see the settings tab. In the icons.abapgit.org repo I do.

**Comment by larshp** [comment]
@sbcgua done, try again

**Comment by larshp** [comment]
also note, github actions is down, since hours ago, https://www.githubstatus.com

**Comment by sbcgua** [comment]
Settings: ok, got it. Will continue a bit later today

**Comment by sbcgua** [comment]
OK, I guess it works now. Have a look.

**Comment by sbcgua** [comment]
Also I adjusted the readme

**Comment by sbcgua** [comment]
really nice tooling out there

**Comment by larshp** [comment]
looks good 🥳 ok to close from my pov

**Comment by larshp** [comment]
username adjusted in https://github.com/abapGit/icon-font/pull/20

**Comment by sbcgua** [comment]
Yeap, thnks ! Closing
